package com.wsc.constants;

public enum EventFilterType
{
    ACADEMIC,
    ALUMNI_FOUNDATION,
    ART_EXHIBITS,
    CAREER_JOBS,
    CONFERENCE_WORKSHOPS,
    FITNESS_RECREATION,
    HEALTH_WELLNESS,
    HOLIDAY_SEASONAL,
    LITERATURE_FILM,
    MUSIC_PERFORMANCES,
    PLANETARIUM_SHOWS,
    SERVICE_VOLUNTEER,
    SOCIAL_EVENTS,
    SPEAKERS_PANELS,
    SPECIAL_INTEREST,
    THEATRE_PERFORMANCES,
    TOURS_VISITS,
    NO_FILTER
}

